//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Application.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Message {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Message() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Application.Resources.Message", typeof(Message).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El tipo de cuenta {0} se grabo correctamente..
        /// </summary>
        internal static string AccountTypeSuccessfullySaved {
            get {
                return ResourceManager.GetString("AccountTypeSuccessfullySaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El tipo de cuenta {0} se actualizó correctamente..
        /// </summary>
        internal static string AccountTypeSuccessfullyUpdated {
            get {
                return ResourceManager.GetString("AccountTypeSuccessfullyUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La categoría {0} se grabo correctamente..
        /// </summary>
        internal static string CategorySuccessfullySaved {
            get {
                return ResourceManager.GetString("CategorySuccessfullySaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La categoría {0} se actualizó correctamente..
        /// </summary>
        internal static string CategorySuccessfullyUpdated {
            get {
                return ResourceManager.GetString("CategorySuccessfullyUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se ha cambiado su contraseña correctamente..
        /// </summary>
        internal static string CorrectPasswordChange {
            get {
                return ResourceManager.GetString("CorrectPasswordChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El empleado {0} se grabo correctamente..
        /// </summary>
        internal static string EmployeeSuccessfullySaved {
            get {
                return ResourceManager.GetString("EmployeeSuccessfullySaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El empleado {0} se actualizo correctamente..
        /// </summary>
        internal static string EmployeeSuccessfullyUpdated {
            get {
                return ResourceManager.GetString("EmployeeSuccessfullyUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La figura {0} se grabo correctamente..
        /// </summary>
        internal static string FigureSuccessfullySaved {
            get {
                return ResourceManager.GetString("FigureSuccessfullySaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La figura {0} se actualizó correctamente..
        /// </summary>
        internal static string FigureSuccessfullyUpdated {
            get {
                return ResourceManager.GetString("FigureSuccessfullyUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El frame {0} se grabo correctamente..
        /// </summary>
        internal static string FrameSuccessfullySaved {
            get {
                return ResourceManager.GetString("FrameSuccessfullySaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El frame {0} se actualizó correctamente..
        /// </summary>
        internal static string FrameSuccessfullyUpdated {
            get {
                return ResourceManager.GetString("FrameSuccessfullyUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El perfil {0} se grabo correctamente..
        /// </summary>
        internal static string RolSuccessfullySaved {
            get {
                return ResourceManager.GetString("RolSuccessfullySaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El perfil {0} se actualizo correctamente..
        /// </summary>
        internal static string RolSuccessfullyUpdated {
            get {
                return ResourceManager.GetString("RolSuccessfullyUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario generado correctamente..
        /// </summary>
        internal static string UserGenerated {
            get {
                return ResourceManager.GetString("UserGenerated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El usuario {0} se actualizo correctamente..
        /// </summary>
        internal static string UserSuccessfullyUpdated {
            get {
                return ResourceManager.GetString("UserSuccessfullyUpdated", resourceCulture);
            }
        }
    }
}
